apis/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.contrib import admin
from . import views




urlpatterns = [
    path('book_list/', views.book_list, name='book_list'),
    path('book_detail/<int:pk>/', views.book_detail, name='book_detail'),
    path('book_det/<int:pk>/', views.book_det, name='book_det'),

    path('book_create/', views.book_create, name='book_create'),
    path('user_list/', views.user_list, name='user_list'),
    path('user_det/<int:pk>/', views.user_det, name='user_det'),
    path('borrow/<int:pk>/', views.borrow, name='borrow_book'),
    path('return_book/<int:pk>/', views.return_book, name='return_book'),
    path('passbook/', views.passbook, name='passbook'),


    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
]

books/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home,  name='home'),
    path('booklist/<int:page>/', views.booklist, name='booklist'),
    path('bookdetail/<int:pk>/', views.bookdetail, name='bookdetail'),    
    path('authorlist/<int:page>/', views.authorlist, name='authorlist'),    
    path('add_book/', views.add_book, name='add_book'),
    path('edit_book/<int:pk>/', views.edit_book, name='edit_book'),
    path('delete_book/<int:pk>/', views.delete_book, name='delete_book'),
    path('add_author/', views.add_author, name='add_author'),
    path('search_book/', views.search_book, name='search_book'),
    path('author_detail/<int:pk>', views.author_detail, name='author_detail'),
        
]

library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('user/', include('members.urls')),
    path('user/', include('passbook.urls')),
    path('api/', include('apis.urls')),
    

]

books/models.py
from django.db import models
from django.db.models import indexes
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.contrib.auth import get_user_model
import datetime
from django.urls import reverse 

#from members.models import MyUser

# Create your models here.
genre = [('ch', 'Charitra'), ('sci', 'science' ), ('hea','health'), ('nov','novel'), ('sto', 'stories'), ]

class Author(models.Model):
    name = models.CharField(max_length=300,)
    dob = models.IntegerField(blank=True, null=True,)
    doe = models.IntegerField(blank=True, null=True)
    detail = models.TextField(blank=True, null=True)

    class Meta:
        indexes = [models.Index(fields=['name', 'detail', ]),]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('authordetail', args=[str(self.id)]) 


class Publication(models.Model):
    name = models.CharField(max_length=200)
    address = models.TextField()

    class Meta:
        ordering = ['-name']
        indexes = [models.Index(fields=['name', ]),]
    
    def __str__(self):
        return self.name
class Book(models.Model):
    doc_id = models.IntegerField(unique=True)
    name = models.CharField(max_length=200, )
    author = models.ForeignKey(Author, blank=True, null=True, on_delete=models.SET_NULL, )
    price = models.DecimalField(max_digits=8, decimal_places=2)
    pages = models.IntegerField()
    genre = models.CharField(max_length=3, choices=genre, default='Novel')
    tags = models.CharField(max_length=300, blank=True, null= True)
    published = models.IntegerField()
    in_stock = models.BooleanField(default=True)
    Wished_by = models.IntegerField(default=0)
    read_by = models.IntegerField(default=0)
    publication = models.ForeignKey(Publication, on_delete=models.SET_NULL, blank=True, null=True,)
    vendor = models.CharField(max_length=200, blank=True, null=True,) 

    class Meta:
        ordering = ['-doc_id']
        indexes = [models.Index(fields=['name', 'tags', 'genre']),]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('bookdetail', args=[str(self.id)]) 
    








    

     
    

books/forms.py
from django import forms
from django.forms import (fields, widgets, Textarea, NumberInput, Select, DateField)
from books.models import Book, Author





class bookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields  = ['doc_id', 'name', 'author', 'price', 'pages', 'genre', 
                        'tags', 'published', 'publication', 'vendor']
        
        widgets = {
            'doc_id': Textarea(attrs={'rows': 1,'class': 'form-control col-8'}),
            'name': Textarea(attrs={ 'rows': 1, 'class': 'form-control col-8'}),
            'author': Select(attrs={ 'rows': 1, 'class': 'form-control col-8'}),
            'price': NumberInput(attrs={'rows': 1,'class': 'form-control col-8'}),
            'pages': NumberInput(attrs={'rows': 1,'class': 'form-control col-8'}),
            'genre': Select(attrs={'class': 'form-control col-8'}),
            'tags': Textarea(attrs={'rows': 1,'class': 'form-control col-8'}),
            'published': NumberInput(attrs={'rows': 1,'class': 'form-control col-8'}),
            'publication': Select(attrs={'rows': 1,'class': 'form-control col-8'}),
            'vendor': Textarea(attrs={'rows': 1,'class': 'form-control col-8'}),
        }
    

class authorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'dob', 'doe', 'detail']

        widgets = {
            'name': Textarea(attrs={'rows': 1, 'class': 'form-control col-8'}),
            'dob': NumberInput(attrs={'rows': 1, 'class': 'form-control col-8'}),
            'doe': NumberInput(attrs={'rows': 1, 'class': 'form-control col-8'}),
            'detail': Textarea(attrs={'rows': 1, 'class': 'form-control col-8'}),
        }
    

books/views.py
from multiprocessing import context
from django.conf import settings
from django.core import paginator
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator
from .forms import bookForm, authorForm
from .models import Author, Book
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .decorators import employee_required
from django.contrib import messages
from django.db.models import F
from itertools import chain

#User = settings.AUTH_USER_MODEL
User=get_user_model()

# Create your views here.


def home(request, ):
    object = Book.objects.filter(genre ='stories')
    context = {'object': object, }
    return render (request, 'books/home.html', context)


def booklist(request, page=1):
    Book_list = Book.objects.all().order_by('doc_id')
    paginator = Paginator(Book_list, 3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
      
    return render(request, 'books/booklist.html', {'page_obj': page_obj})


def bookdetail(request, pk):
    context = {'object':get_object_or_404(Book, pk)}
    return render(request, 'books/bookdetail.html', context=context)
    


def authorlist(request, page=1):
    author_list = Author.objects.all().order_by('name')
    paginator = Paginator(author_list, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
      
    return render(request, 'books/authorlist.html', {'page_obj': page_obj})


def author_detail(request, pk):
    context = {'an_author':Author.objects.get(id=pk)}
    print(context)
    book_list = Book.objects.filter(author = pk)
    paginator = Paginator(book_list, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context['page_obj'] = page_obj
    print(context)
    return render(request, 'books/author_detail.html', context=context)




@login_required(login_url='/user/login/')
@employee_required
def add_book(request):
    form = bookForm()
    context = {'form':form}
    if request.method == 'POST':
        form = bookForm(request.POST)        
        if form.is_valid():
            
            docid = form.cleaned_data['doc_id']
            name = form.cleaned_data['name']
            author = form.cleaned_data['author']
            price = form.cleaned_data['price']
            pages = form.cleaned_data['pages']
            genre = form.cleaned_data['genre']
            tags = form.cleaned_data['tags']
            published = form.cleaned_data['published']
            publication = form.cleaned_data['publication']
            vendor = form.cleaned_data['vendor']

            book_obj = Book.objects.create(doc_id= docid, name= name, author=author, 
                            price= price, pages= pages, genre= genre, tags=tags, published= published,
                                publication= publication, vendor= vendor)
            book_obj.save()
            messages.success(request, f'{book_obj.name} is added successfully.')

            return redirect('dashboard')

        else:
           messages.warning(request, 'Something went wrong. Contact sam..!') 

    return render(request, 'books/add_book.html', context)



@login_required(login_url='/user/login/')
@employee_required
def edit_book(request, pk):
    context = {} 
    book_obj = Book.objects.get(id = pk)
    form = bookForm(request.POST or None, instance=book_obj )
    if form.is_valid():
        form.save()
        messages.success(request, f'{book_obj.name} is updated successfully.') 
       
    context['form'] = form
    return render(request, 'books/edit_book.html', context)


@login_required(login_url='/user/login/')
@employee_required
def delete_book(request, pk):
    book_obj = Book.objects.get(id = pk)
    book_name = book_obj.name
    book_obj.delete()
    messages.success(request, f'{book_obj.name} is deleted successfully.')    
    return redirect('home', )
    
    



@login_required(login_url='/user/login/')
@employee_required
def add_author(request):
    form = authorForm()
    context = {'form':form}
    if request.method == 'POST':
        form = authorForm(request.POST)
        if form.is_valid:
            print("true")
            print(f"----{form}----")
            name= form.cleaned_data['name']
            dob= form.cleaned_data['dob']
            doe= form.cleaned_data['doe']
            detail= form.cleaned_data['detail']

            anauthor = Author.objects.create(name= name, dob= dob, doe= doe, detail= detail)
            anauthor.save()
            messages.success(request, f'{anauthor.name} is added successfully.')
            return redirect('dashboard')
        else:
             messages.warning(request, 'Something went wrong.')

    return render(request, 'books/add_author.html', context)


def search_book(request):
    books_obj = Book.objects.filter(name__icontains = "a") 
    #authur_obj = Author.objects.filter(name__icontains = qs)
    
    paginator = Paginator(books_obj, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'books/search_list.html', {'page_obj': page_obj})

books/templates/books/add_author.html
{%extends "books/base.html"%}

{%block content%}
    <div class="container">
        <form method="post" action="{% url 'add_author'%}" class="">
          {% csrf_token %}
          <div>  {{form.as_p}} </div>
            <button type="submit" class="btn btn-primary btn-sm">Add Author</button>
        </form>
        </div>
    
    
{%endblock content%}

books/templates/books/add_book.html
{%extends "books/base.html"%}

{%block content%}
    <div class="container">
        <form action="" class="">
          {% csrf_token %}
          <div>  {{form.as_p}} </div>
            <button type="submit" class="btn btn-primary btn-sm">Submit</button>
        </form>
        </div>
    
    
{%endblock content%}

books/templates/books/author_detail.html
{%extends "books/base.html"%}

{%block content%}

<br>

<div class="container">
    <h3>{{an_author.name}}</h3>
</div>
<br>

<div class="container">


    <table class="table table-sm table-bordered">
        <thead>
            <tr>
                <th scope="col">Doc id </th>
                <th scope="col">Book Name</th>

                <th scope="col">Pages</th>
                <th scope="col">genre</th>
                <th scope="col">Available</th>
                <th scope="col">Publication</th>
                <th>Add to Wishlist</th>
                {%if user.is_employee %}
                <th>Borrow</th>
                {%endif%}
            </tr>
        </thead>
        <tbody>
            {%for book in page_obj%}
            <tr>
                <th scope="row">{{book.doc_id}}</th>
                <td>{{book.name}}</td>

                <td>{{book.pages}}</td>
                <td>{{book.get_genre_display}}</td>
                <!--For choice fields get_{model-field}_dispaly-->
                <td>{{book.in_stock}}</td>
                <td>{{book.publication}}</td>
                <td><button title="Add to wishlist" class="btn-primary" id="{{book.id}}">+ </button> </td>
                {%if user.is_employee%}
                <td>
                    {%if book.in_stock%}
                    <a href="{%url 'borrow' book.id%}">issue</a> {%endif%}
                </td>
                {%endif%}
            </tr>
            {%endfor%}
        </tbody>
    </table>
</div>
<div class="pagination justify-content-end px-4">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a class="px-2" href="?page=1">&laquo; first</a>
        <a class="px-2" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a class="px-2" href="?page={{ page_obj.next_page_number }}">next</a>
        <a class="px-2" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>



{%endblock content%}



{% block jscripts %}



{% endblock jscripts %}

books/templates/books/authorlist.html
{%extends "books/base.html"%}

{%block content%}
<br>
{% for author in page_obj %}

<div class="container"> <a href="{%url 'author_detail' author.id%}">
    {{author.name}} </a>
    <small> {{author.id}}
        {% if author.dob %}{{author.dob}}-{% endif %}{% if author.doe %}{{author.doe}}{% endif %}
    </small> <br>
    <p>{{author.detail}}</p>
    <br>
    <hr>
</div>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{%endblock content%}

books/templates/books/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{%static 'article/main.css'%}">

    <title>Library</title>
</head>

<body>

    <header class="sticky-top">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark   ">
            <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-xl-around " id="collapse_target">
                <ul class="navbar-nav px-2">
                    <li class="nav-item px-4">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item px-4">
                        <a class="nav-link" href="{% url 'booklist' 1%}">All Books</a>
                    </li>
                    <li class="nav-item px-4">
                        <a class="nav-link" href="{% url 'authorlist' 1%}">All Authors</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item px-4">
                        <a class="nav-link" href="#">{{user.member_id}}</a>
                    </li>

                    <li class="nav-item px-4">
                        <a class="nav-link" href="{%url 'signout' %}">Sign Out</a>
                    </li>

                    <li class="nav-item px-4">
                        <a class="nav-link" href="{%url 'dashboard'%}">Dashboard</a>
                    </li>
                    {%else%}
                    <li class="nav-item px-4">
                        <a class="nav-link" href="{%url 'signin'%}">Log in</a>
                    </li>
                    {%endif%}

                </ul>
                <form class="d-flex" method=POST action="{%url 'search_book'%}">
                    {%csrf_token%}
                    <input type="search" aria-label="Search" class="form-control " placeholder="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>

        </nav>
    </header>


    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
    </div>

    {% block content %}{% endblock %}



    {% block jscripts %}{% endblock %}

</body>

</html>

books/templates/books/bookdetail.html
{%extends "books/base.html"%}

{%block content%}
    
{%endblock content%}

books/templates/books/booklist.html
{%extends "books/base.html"%}

{%block content%}



<div class="container">
    <br>
    <table class="table table-sm table-bordered">
        <thead>
            <tr>
                <th scope="col">Doc id </th>
                <th scope="col">Book Name</th>
                <th scope="col">Author</th>
                <th scope="col">Pages</th>
                <th scope="col">genre</th>
                <th scope="col">Available</th>
                <th scope="col">Publication</th>
                <th>Add to Wishlist</th>
                {%if user.is_employee %}
                <th>Edit Books</th>
                
                <th>Delete Book</th>
                {%else%}
                <th>Borrow Book</th>
                {%endif%}
                
            </tr>
        </thead>
        <tbody>
            {%for book in page_obj%}
            <tr>
                <th scope="row">{{book.doc_id}}</th>
                <td>{{book.name}}</td>
                <td>{{book.author}}</td>
                <td>{{book.pages}}</td>
                <td>{{book.get_genre_display}}</td><!--For choice fields get_{model-field}_dispaly-->
                <td>{{book.in_stock}}</td>
                <td>{{book.publication}}</td>
                <td><button title="Add to wishlist" class="btn-primary" id="{{book.id}}">+ </button> </td>

                {%if user.is_employee%}
                <td>                   
                    <a href="{%url 'edit_book' book.id%}">Edit- {{book.id}}</a></td>
                   
                <td>

                    {%if book.in_stock%}
                    
                    <a href="{%url 'delete_book' book.id%}">Delete</a> </td> {%endif%}
                    {%else%}
                    <td> <a href="{%url 'borrow' book.id%}">Borrow</a> </td> 
                    {%endif%}
            </tr>
            {%endfor%}
        </tbody>
    </table>
</div>
<div class="pagination justify-content-end px-4">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a class="px-2" href="?page=1">&laquo; first</a>
        <a class="px-2" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a class="px-2" href="?page={{ page_obj.next_page_number }}">next</a>
        <a class="px-2" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>



{%endblock content%}



{% block jscripts %}



{% endblock jscripts %}

books/templates/books/dashboard1.html
{%extends "books/base.html"%}

{%block content%}
    <div class="row">
        <div>
            <ul>
                <li>
                    <a class="" href="{%url 'signup'%}" >Add a member</a>
                </li>    
                <li>
                  <a class="" href="{%url 'add_book'%}" >Add a Book</a>
              </li>             
            </ul>
        </div>
        <div class="container">            
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">id No. </th>
                    <th scope="col">member</th>
                    <th scope="col">book</th>
                    <th scope="col">borrow_date</th>
                    <th scope="col">due_date</th>
                    <th scope="col">return_date</th>
                    <th scope="col">due_charges</th>
                  </tr>
                </thead>
                <tbody>
                    {%for obj in obj_pass%}
                  <tr>
                    <th scope="row">{{obj.id}}</th>
                    <td>{{obj.member}}</td>
                    <td>{{obj.book}}</td>
                    <td>{{obj.borrow_date}}</td>
                    <td>{{obj.due_date}}</td>
                    <td>{{obj.return_date}}</td>
                    <td>{{obj.due_charges}}</td>
                  </tr>
                 {%endfor%}
                </tbody>
              </table>
        </div>
    </div>
{%endblock content%}

books/templates/books/edit_book.html
{%extends "books/base.html"%}

{%block content%}
<div class="container">
    <form method="post" class="">
      {% csrf_token %}
      <div>  {{form.as_p}} </div>
        <button type="submit" class="btn btn-primary btn-sm">Edit Book</button>
    </form>
    </div>

    
{%endblock content%}

books/templates/books/home.html
{%extends "books/base.html"%}

{%block content%}

<div class="container"><h2>Welcome to the Library ..!</h2></div> 
<div class="container"> Go to All books to borrow books.</div>
    

{%endblock content%}

books/templates/books/search_list.html
{%extends "books/base.html"%}

{%block content%}

<div class="pagination justify-content-end px-4">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a class="px-2" href="?page=1">&laquo; first</a>
        <a class="px-2" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a class="px-2" href="?page={{ page_obj.next_page_number }}">next</a>
        <a class="px-2" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{%endblock content%}